In [1]:
# Install necessary libraries
!pip3 install adtk  # data analysis and exploration
!pip install ipython-sql

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


In [2]:
#Import required modules:
import pandas as pd
import numpy as np
import sqlite3
pd.options.display.float_format = '{:,.2f}'.format
%matplotlib inline
import warnings
import time
import calendar
from datetime import datetime as dt
from adtk.data import validate_series
warnings.filterwarnings("ignore")

In [3]:
# Read CSV to dataframe mh:
mh = pd.read_csv('StudentMentalhealthnew.csv')

In [4]:
#Call the first 2 rows, (axis 0) of dataframe:
mh.head(2)

date_time gender  age        course_name   department  \
0  2020/07/08 12:02:00      F   18        Engineering  Engineering   
1  2020/07/08 12:04:00      M   21  Islamic education         RSEP   

   study_year   cgpa_score depression anxiety panic_attack specialist_hlp  
0           1  3.00 - 3.49          Y       N            Y              N  
1           2  3.00 - 3.49          N       Y            N              N

In [5]:
#Call for mh dataframe datatypes:
mh.dtypes

date_time         object
gender            object
age                int64
course_name       object
department        object
study_year         int64
cgpa_score        object
depression        object
anxiety           object
panic_attack      object
specialist_hlp    object
dtype: object

In [6]:
cnn = sqlite3.connect('temp.db')

In [7]:
mh.to_sql('studmh', cnn, if_exists='replace')

101

In [8]:
%load_ext sql

In [9]:
%sql sqlite:///temp.db

In [10]:
%%sql
SELECT *
FROM studmh
LIMIT 3

 * sqlite:///temp.db
Done.


[(0, '2020/07/08 12:02:00', 'F', 18, 'Engineering', 'Engineering', 1, '3.00 - 3.49', 'Y', 'N', 'Y', 'N'),
 (1, '2020/07/08 12:04:00', 'M', 21, 'Islamic education', 'RSEP', 2, '3.00 - 3.49', 'N', 'Y', 'N', 'N'),
 (2, '2020/07/08 12:05:00', 'M', 19, 'Business Information Tech', 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N')]

In [27]:
%%sql
DROP TABLE IF EXISTS tempstudmh;
CREATE TABLE tempstudmh
(
    date_time int
    ,gender varchar(10)
    , age int
    , department varchar (20)
    , study_year int
    , cgpa_score varchar (10)
    , depression varchar (10)
    , anxiety varchar (10)
    , panic_attack varchar (10)
    , specialist_hlp varchar (10)
);

SELECT *
FROM tempstudmh

 * sqlite:///temp.db
Done.
Done.
Done.


[]

In [28]:
%%sql
INSERT INTO tempstudmh
SELECT date_time, gender, age, department, study_year, cgpa_score, depression, anxiety, panic_attack, specialist_hlp
FROM studmh;

SELECT *
FROM tempstudmh;


 * sqlite:///temp.db
101 rows affected.
Done.


[('2020/07/08 12:02:00', 'F', 18, 'Engineering', 1, '3.00 - 3.49', 'Y', 'N', 'Y', 'N'),
 ('2020/07/08 12:04:00', 'M', 21, 'RSEP', 2, '3.00 - 3.49', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:05:00', 'M', 19, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 12:06:00', 'F', 22, 'Law', 3, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:13:00', 'M', 23, 'Mathematics', 4, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:31:00', 'M', 19, 'Engineering', 2, '3.50 - 4.00', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 12:32:00', 'F', 23, 'RSEP', 2, '3.50 - 4.00', 'Y', 'N', 'Y', 'N'),
 ('2020/07/08 12:33:00', 'F', 18, 'Information Technology', 1, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:35:00', 'F', 19, 'Economics', 2, '2.50 - 2.99', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:39:00', 'M', 18, 'RSEP', 1, '3.50 - 4.00', 'N', 'Y', 'Y', 'N'),
 ('2020/07/08 12:39:00', 'F', 20, 'Psychology', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:39:00', 'F', 24, 'Engineering', 3, '3.50 - 4.00', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:40:00', 'F', 18, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:41:00', 'M', 19, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:43:00', 'F', 18, 'Economics', 2, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:43:00', 'M', 24, 'Information Technology', 3, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:46:00', 'F', 24, 'Economics', 3, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:52:00', 'F', 24, 'Sciences', 4, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:05:00', 'F', 20, 'Information Technology', 2, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 13:07:00', 'F', 18, 'Sciences', 2, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:12:00', 'F', 19, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 13:13:00', 'F', 18, 'Engineering', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:13:00', 'F', 24, 'Information Technology', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:15:00', 'F', 24, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:17:00', 'F', 23, 'Information Technology', 3, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:29:00', 'F', 18, 'Economics', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:35:00', 'F', 19, 'Engineering', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:41:00', 'M', 18, 'Engineering', 2, '3.00 - 3.49', 'Y', 'Y', 'N', 'N'),
 ('2020/07/08 13:58:00', 'F', 24, 'Information Technology', 3, '3.50 - 4.00', 'Y', 'Y', 'Y', 'Y'),
 ('2020/07/08 14:05:00', 'F', 24, 'Information Technology', 4, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:27:00', 'F', 23, 'Economics', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:29:00', 'M', 18, 'Information Technology', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:29:00', 'M', 19, 'Information Technology', 1, '3.50 - 4.00', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 14:31:00', 'M', 18, 'Information Technology', 2, '3.50 - 4.00', 'Y', 'Y', 'N', 'Y'),
 ('2020/07/08 14:41:00', 'F', 19, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 14:43:00', 'F', 18, 'Engineering', 1, '2.00 - 2.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:43:00', 'F', 18, 'Law', 3, '3.00 - 3.49', 'Y', 'Y', 'N', 'N'),
 ('2020/07/08 14:45:00', 'F', 19, 'Information Technology', 1, '2.50 - 2.99', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 14:47:00', 'F', 18, 'RSEP', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:56:00', 'F', 24, 'Engineering', 2, '2.50 - 2.99', 'Y', 'N', 'Y', 'Y'),
 ('2020/07/08 14:57:00', 'F', 24, 'Information Technology', 3, '3.00 - 3.49', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 14:57:00', 'F', 22, 'Engineering', 4, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:58:00', 'F', 20, 'RSEP', 2, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 15:07:00', 'M', 19, 'Information Technology', 1, '0 - 1.99', 'N', 'N', 'N', 'N'),
 ('2020/07/08 15:08:00'

In [33]:
%%sql
CREATE INDEX indx ON tempstudmh(date_time)

 * sqlite:///temp.db
Done.


[]

In [34]:
%%sql
SELECT *
FROM tempstudmh

 * sqlite:///temp.db
Done.


[('2020/07/08 12:02:00', 'F', 18, 'Engineering', 1, '3.00 - 3.49', 'Y', 'N', 'Y', 'N'),
 ('2020/07/08 12:04:00', 'M', 21, 'RSEP', 2, '3.00 - 3.49', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:05:00', 'M', 19, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 12:06:00', 'F', 22, 'Law', 3, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:13:00', 'M', 23, 'Mathematics', 4, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:31:00', 'M', 19, 'Engineering', 2, '3.50 - 4.00', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 12:32:00', 'F', 23, 'RSEP', 2, '3.50 - 4.00', 'Y', 'N', 'Y', 'N'),
 ('2020/07/08 12:33:00', 'F', 18, 'Information Technology', 1, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:35:00', 'F', 19, 'Economics', 2, '2.50 - 2.99', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:39:00', 'M', 18, 'RSEP', 1, '3.50 - 4.00', 'N', 'Y', 'Y', 'N'),
 ('2020/07/08 12:39:00', 'F', 20, 'Psychology', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:39:00', 'F', 24, 'Engineering', 3, '3.50 - 4.00', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:40:00', 'F', 18, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:41:00', 'M', 19, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:43:00', 'F', 18, 'Economics', 2, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:43:00', 'M', 24, 'Information Technology', 3, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:46:00', 'F', 24, 'Economics', 3, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:52:00', 'F', 24, 'Sciences', 4, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:05:00', 'F', 20, 'Information Technology', 2, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 13:07:00', 'F', 18, 'Sciences', 2, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:12:00', 'F', 19, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 13:13:00', 'F', 18, 'Engineering', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:13:00', 'F', 24, 'Information Technology', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:15:00', 'F', 24, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:17:00', 'F', 23, 'Information Technology', 3, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:29:00', 'F', 18, 'Economics', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:35:00', 'F', 19, 'Engineering', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:41:00', 'M', 18, 'Engineering', 2, '3.00 - 3.49', 'Y', 'Y', 'N', 'N'),
 ('2020/07/08 13:58:00', 'F', 24, 'Information Technology', 3, '3.50 - 4.00', 'Y', 'Y', 'Y', 'Y'),
 ('2020/07/08 14:05:00', 'F', 24, 'Information Technology', 4, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:27:00', 'F', 23, 'Economics', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:29:00', 'M', 18, 'Information Technology', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:29:00', 'M', 19, 'Information Technology', 1, '3.50 - 4.00', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 14:31:00', 'M', 18, 'Information Technology', 2, '3.50 - 4.00', 'Y', 'Y', 'N', 'Y'),
 ('2020/07/08 14:41:00', 'F', 19, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 14:43:00', 'F', 18, 'Engineering', 1, '2.00 - 2.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:43:00', 'F', 18, 'Law', 3, '3.00 - 3.49', 'Y', 'Y', 'N', 'N'),
 ('2020/07/08 14:45:00', 'F', 19, 'Information Technology', 1, '2.50 - 2.99', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 14:47:00', 'F', 18, 'RSEP', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:56:00', 'F', 24, 'Engineering', 2, '2.50 - 2.99', 'Y', 'N', 'Y', 'Y'),
 ('2020/07/08 14:57:00', 'F', 24, 'Information Technology', 3, '3.00 - 3.49', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 14:57:00', 'F', 22, 'Engineering', 4, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:58:00', 'F', 20, 'RSEP', 2, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 15:07:00', 'M', 19, 'Information Technology', 1, '0 - 1.99', 'N', 'N', 'N', 'N'),
 ('2020/07/08 15:08:00'

In [34]:
%%sql
SELECT *
FROM tempstudmh

 * sqlite:///temp.db
Done.


[('2020/07/08 12:02:00', 'F', 18, 'Engineering', 1, '3.00 - 3.49', 'Y', 'N', 'Y', 'N'),
 ('2020/07/08 12:04:00', 'M', 21, 'RSEP', 2, '3.00 - 3.49', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:05:00', 'M', 19, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 12:06:00', 'F', 22, 'Law', 3, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:13:00', 'M', 23, 'Mathematics', 4, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:31:00', 'M', 19, 'Engineering', 2, '3.50 - 4.00', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 12:32:00', 'F', 23, 'RSEP', 2, '3.50 - 4.00', 'Y', 'N', 'Y', 'N'),
 ('2020/07/08 12:33:00', 'F', 18, 'Information Technology', 1, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:35:00', 'F', 19, 'Economics', 2, '2.50 - 2.99', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:39:00', 'M', 18, 'RSEP', 1, '3.50 - 4.00', 'N', 'Y', 'Y', 'N'),
 ('2020/07/08 12:39:00', 'F', 20, 'Psychology', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:39:00', 'F', 24, 'Engineering', 3, '3.50 - 4.00', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:40:00', 'F', 18, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 12:41:00', 'M', 19, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:43:00', 'F', 18, 'Economics', 2, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 12:43:00', 'M', 24, 'Information Technology', 3, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:46:00', 'F', 24, 'Economics', 3, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 12:52:00', 'F', 24, 'Sciences', 4, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:05:00', 'F', 20, 'Information Technology', 2, '3.50 - 4.00', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 13:07:00', 'F', 18, 'Sciences', 2, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:12:00', 'F', 19, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 13:13:00', 'F', 18, 'Engineering', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:13:00', 'F', 24, 'Information Technology', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:15:00', 'F', 24, 'Engineering', 1, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:17:00', 'F', 23, 'Information Technology', 3, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 13:29:00', 'F', 18, 'Economics', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:35:00', 'F', 19, 'Engineering', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 13:41:00', 'M', 18, 'Engineering', 2, '3.00 - 3.49', 'Y', 'Y', 'N', 'N'),
 ('2020/07/08 13:58:00', 'F', 24, 'Information Technology', 3, '3.50 - 4.00', 'Y', 'Y', 'Y', 'Y'),
 ('2020/07/08 14:05:00', 'F', 24, 'Information Technology', 4, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:27:00', 'F', 23, 'Economics', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:29:00', 'M', 18, 'Information Technology', 2, '3.00 - 3.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:29:00', 'M', 19, 'Information Technology', 1, '3.50 - 4.00', 'N', 'N', 'Y', 'N'),
 ('2020/07/08 14:31:00', 'M', 18, 'Information Technology', 2, '3.50 - 4.00', 'Y', 'Y', 'N', 'Y'),
 ('2020/07/08 14:41:00', 'F', 19, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 14:43:00', 'F', 18, 'Engineering', 1, '2.00 - 2.49', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:43:00', 'F', 18, 'Law', 3, '3.00 - 3.49', 'Y', 'Y', 'N', 'N'),
 ('2020/07/08 14:45:00', 'F', 19, 'Information Technology', 1, '2.50 - 2.99', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 14:47:00', 'F', 18, 'RSEP', 1, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:56:00', 'F', 24, 'Engineering', 2, '2.50 - 2.99', 'Y', 'N', 'Y', 'Y'),
 ('2020/07/08 14:57:00', 'F', 24, 'Information Technology', 3, '3.00 - 3.49', 'N', 'Y', 'N', 'N'),
 ('2020/07/08 14:57:00', 'F', 22, 'Engineering', 4, '3.50 - 4.00', 'N', 'N', 'N', 'N'),
 ('2020/07/08 14:58:00', 'F', 20, 'RSEP', 2, '3.00 - 3.49', 'Y', 'N', 'N', 'N'),
 ('2020/07/08 15:07:00', 'M', 19, 'Information Technology', 1, '0 - 1.99', 'N', 'N', 'N', 'N'),
 ('2020/07/08 15:08:00'

In [45]:
%%sql
SELECT department, study_year, cgpa_score, count(date_time)
FROM tempstudmh
WHERE depression = 'Y'
AND anxiety = 'Y'
AND panic_attack = 'Y'
GROUP BY department;

 * sqlite:///temp.db
Done.


[('Engineering', 3, '3.00 - 3.49', 1),
 ('Information Technology', 1, '3.00 - 3.49', 5),
 ('Media', 2, '3.50 - 4.00', 1),
 ('Psychology', 1, '3.50 - 4.00', 1),
 ('Sciences', 4, '3.00 - 3.49', 2)]

In [53]:
%%sql
SELECT department, study_year, cgpa_score, count(date_time)
FROM tempstudmh
WHERE (depression = 'Y'
OR anxiety = 'Y'
OR panic_attack = 'Y')
GROUP BY department;

 * sqlite:///temp.db
Done.


[('Arts', 1, '2.50 - 2.99', 1),
 ('Economics', 2, '3.50 - 4.00', 2),
 ('Engineering', 1, '3.00 - 3.49', 17),
 ('Information Technology', 1, '3.00 - 3.49', 22),
 ('Law', 3, '3.00 - 3.49', 4),
 ('Linguistics', 2, '3.50 - 4.00', 4),
 ('Media', 1, '3.50 - 4.00', 2),
 ('Psychology', 1, '3.50 - 4.00', 2),
 ('RSEP', 2, '3.00 - 3.49', 4),
 ('Sciences', 4, '3.00 - 3.49', 6)]

 * sqlite:///temp.db
Done.


[(26, 75)]

In [149]:
%%sql



 * sqlite:///temp.db
Done.
Done.
Done.
(sqlite3.OperationalError) near "FROM": syntax error
[SQL: FROM tempstudmh;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)


In [154]:
%%sql
SELECT department, study_year, cgpa_score, count(date_time)
FROM tempstudmh
WHERE (depression = 'Y'
OR anxiety = 'Y'
OR panic_attack = 'Y')
GROUP BY cgpa_score ;

 * sqlite:///temp.db
Done.


[('Law', 3, '0 - 1.99', 1),
 ('Engineering', 2, '2.00 - 2.49', 1),
 ('Information Technology', 1, '2.50 - 2.99', 3),
 ('Engineering', 1, '3.00 - 3.49', 28),
 ('Engineering', 2, '3.50 - 4.00', 31)]

In [151]:
%%sql
SELECT department, study_year, cgpa_score, count(date_time)
FROM tempstudmh
WHERE depression = 'Y'
AND anxiety = 'Y'
GROUP BY cgpa_score;

 * sqlite:///temp.db
Done.


[('Information Technology', 1, '2.50 - 2.99', 1),
 ('Information Technology', 1, '3.00 - 3.49', 9),
 ('Sciences', 2, '3.50 - 4.00', 8)]

In [152]:
%%sql
SELECT department, study_year, cgpa_score, count(date_time)
FROM tempstudmh
WHERE (depression = 'Y'
OR anxiety = 'Y')
GROUP BY cgpa_score;

 * sqlite:///temp.db
Done.


[('Information Technology', 1, '2.50 - 2.99', 3),
 ('Engineering', 1, '3.00 - 3.49', 25),
 ('RSEP', 2, '3.50 - 4.00', 23)]

Querying anxiety and depression grouped by department shows a trend in students experiencing anxiety and depression with CGPA over 3.00.

In [60]:
%%sql
SELECT *
FROM tempstudmh
WHERE anxiety = 'Y'
AND depression = 'Y'
AND panic_attack = 'Y' 
GROUP BY department

 * sqlite:///temp.db
Done.


[('2020/07/08 15:48:00', 'F', 20, 'Engineering', 3, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 12:05:00', 'M', 19, 'Information Technology', 1, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/13 10:11:26', 'F', 24, 'Media', 2, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/13 11:46:13', 'F', 18, 'Psychology', 1, '3.50 - 4.00', 'Y', 'Y', 'Y', 'N'),
 ('2020/07/08 12:52:00', 'F', 24, 'Sciences', 4, '3.00 - 3.49', 'Y', 'Y', 'Y', 'N')]

Of 101 students, 5 experienced all three concerns depression, anxiety and panic attack, all of which have CGPA of 3.00 > none of which sought specialst help. There is no defining trend regarding department or study year in this sample group.

In [62]:
%%sql
SELECT *
FROM tempstudmh
WHERE specialist_hlp = 'Y';


 * sqlite:///temp.db
Done.


[('2020/07/08 13:58:00', 'F', 24, 'Information Technology', 3, '3.50 - 4.00', 'Y', 'Y', 'Y', 'Y'),
 ('2020/07/08 14:31:00', 'M', 18, 'Information Technology', 2, '3.50 - 4.00', 'Y', 'Y', 'N', 'Y'),
 ('2020/07/08 14:56:00', 'F', 24, 'Engineering', 2, '2.50 - 2.99', 'Y', 'N', 'Y', 'Y'),
 ('2020/07/08 15:27:00', 'F', 23, 'Arts', 1, '2.50 - 2.99', 'Y', 'N', 'Y', 'Y'),
 ('2020/07/08 15:57:00', 'F', 19, 'Information Technology', 1, '3.50 - 4.00', 'Y', 'N', 'Y', 'Y'),
 ('2020/07/13 10:33:47', 'F', 18, 'Psychology', 1, '3.50 - 4.00', 'Y', 'Y', 'N', 'Y')]

In [120]:
%%sql
SELECT count(*), gender, study_year, cgpa_score
FROM tempstudmh
WHERE anxiety = 'Y'
AND depression = 'Y'
AND panic_attack = 'Y' 
AND specialist_hlp = 'Y'
GROUP BY department

 * sqlite:///temp.db
Done.


[(1, 'F', 3, '3.50 - 4.00')]

Of the 101 students only 1, repied yes to all fields - female, 3rd year student with 3.5-4 CGPA. 

In [155]:
%%sql
SELECT
SUM(CASE WHEN gender = 'M' THEN 1 ELSE 0 END) AS male_count,
  SUM(CASE WHEN gender = 'F' THEN 1 ELSE 0 END) AS female_count
FROM tempstudmh;


 * sqlite:///temp.db
Done.


[(26, 75)]

Running a query on gender split between respondents, 101 is a small sample, and gender split may skew data outcomes.